Return nil when getting a version
If there's no log_data on a model instance and caller tries to get a
version of the model using `#at_version(v)` or `#at(version: v)`, return
`nil` instead of raising `NoMethodError` (undefined method `version' for
nil:NilClass).