Fix error when running ./bin/setup with Rails 5.0.0.1
When trying to set up development environment via `./bin/setup` using
a new RVM gemset with Ruby 2.3.0 and Rails 5.0.0.1, the
following error occures:

```
Resolving dependencies...
The Gemfile's dependencies are satisfied
Database 'dummy_development' already exists
Database 'logidze_test' already exists
rake aborted!
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration:0x00000001de17e0>
Did you mean?  asset_host
[ ... STACKTRACE ... ]
```

This patch fixes the error by checking if `Rails::Application::Configuration`
responds to `#assets` first. An alternative solution is to uncomment the line
`# require 'sprockets/railtie` in `spec/dummy/config/application.rb`